### ISSUE TITLE
Wrong fields in the lucene index corrupted SStable

### ISSUE THREAD

**Issue by rkgurram** [Stratio/cassandra-lucene-index#108]
Hi,
    We are using cassandra 2.1.8 and Cassandra lucene index 2.1.8.2, while creating a index we have by mistake given one of the field names as wrong, without realizing this has led to the corruption of the SStable and now cassandra is down.

I have tried to use sstablescrub to clean up cassandra tables, looks like most of the tables are clean but still for some tables I get the following error.

ERROR 20:59:27 'schema' is invalid : No column definition 'DURATION' for mapper 'DURATION'
'schema' is invalid : No column definition 'DURATION' for mapper 'DURATION'

The name of the field had to be "CONNECTION_DURATION" but by mistake we specified as "DURATION". What I am more surprised is that this error shows up not just for the table where the mistake has occured but for other tables too. 

 I really want to get my cassandra nodes up without losing the data, I do not care if I need to sacrifice this one table for that but for now I am at my wits end as to how to get it back on its feet.

Any help would be appreciated

Is there a way where I can delete just this table and the Lucene Index related to it and bring up cassandra.

Regards
-Ravi

**Comment by adelapena** [comment]
Hi,
Lucene index never writes SStables, so I can't figure out how can it corrupt them. That said, how do you know the other tables are corrupted? Can you provide the full log trace of the nodes that are unable to start?

**Comment by rkgurram** [comment]
Hi,
      Here is the output from sstablescrub from two of my tables, the keyspace is "cybersparta" and table is "asalogevents". The table is the one that had the wrong field. Below I have another table that has nothing to do with the corrupted index..

=========================================================================

backup                                             internetresources-59fab6a0-c9fd-11e5-b4a3-93ac61d720ce   windowslogevents-f5c2b200-c9b1-11e5-b4a3-93ac61d720ce
[cybersparta@cyber1 cybersparta]$ sstablescrub --debug cybersparta asalogevents
ERROR 00:15:47 'schema' is invalid : No column definition 'DURATION' for mapper 'DURATION'
'schema' is invalid : No column definition 'DURATION' for mapper 'DURATION'
com.stratio.cassandra.lucene.IndexException: 'schema' is invalid : No column definition 'DURATION' for mapper 'DURATION'
        at com.stratio.cassandra.lucene.IndexConfig.parseSchema(IndexConfig.java:204)
        at com.stratio.cassandra.lucene.IndexConfig.<init>(IndexConfig.java:74)
        at com.stratio.cassandra.lucene.Index.validateOptions(Index.java:194)
        at org.apache.cassandra.db.index.SecondaryIndex.createInstance(SecondaryIndex.java:364)
        at org.apache.cassandra.db.index.SecondaryIndexManager.addIndexedColumn(SecondaryIndexManager.java:281)
        at org.apache.cassandra.db.ColumnFamilyStore.<init>(ColumnFamilyStore.java:367)
        at org.apache.cassandra.db.ColumnFamilyStore.createColumnFamilyStore(ColumnFamilyStore.java:504)
        at org.apache.cassandra.db.ColumnFamilyStore.createColumnFamilyStore(ColumnFamilyStore.java:475)
        at org.apache.cassandra.db.Keyspace.initCf(Keyspace.java:339)
        at org.apache.cassandra.db.Keyspace.<init>(Keyspace.java:279)
        at org.apache.cassandra.db.Keyspace.open(Keyspace.java:121)
        at org.apache.cassandra.db.Keyspace.openWithoutSSTables(Keyspace.java:104)
        at org.apache.cassandra.tools.StandaloneScrubber.main(StandaloneScrubber.java:72)
[cybersparta@cyber1 cybersparta]$


========================================================

[cybersparta@cyber1 cybersparta]$ sstablescrub --debug cybersparta accounts
ERROR 00:18:59 'schema' is invalid : No column definition 'DURATION' for mapper 'DURATION'
'schema' is invalid : No column definition 'DURATION' for mapper 'DURATION'
com.stratio.cassandra.lucene.IndexException: 'schema' is invalid : No column definition 'DURATION' for mapper 'DURATION'
        at com.stratio.cassandra.lucene.IndexConfig.parseSchema(IndexConfig.java:204)
        at com.stratio.cassandra.lucene.IndexConfig.<init>(IndexConfig.java:74)
        at com.stratio.cassandra.lucene.Index.validateOptions(Index.java:194)
        at org.apache.cassandra.db.index.SecondaryIndex.createInstance(SecondaryIndex.java:364)
        at org.apache.cassandra.db.index.SecondaryIndexManager.addIndexedColumn(SecondaryIndexManager.java:281)
        at org.apache.cassandra.db.ColumnFamilyStore.<init>(ColumnFamilyStore.java:367)
        at org.apache.cassandra.db.ColumnFamilyStore.createColumnFamilyStore(ColumnFamilyStore.java:504)
        at org.apache.cassandra.db.ColumnFamilyStore.createColumnFamilyStore(ColumnFamilyStore.java:475)
        at org.apache.cassandra.db.Keyspace.initCf(Keyspace.java:339)
        at org.apache.cassandra.db.Keyspace.<init>(Keyspace.java:279)
        at org.apache.cassandra.db.Keyspace.open(Keyspace.java:121)
        at org.apache.cassandra.db.Keyspace.openWithoutSSTables(Keyspace.java:104)
        at org.apache.cassandra.tools.StandaloneScrubber.main(StandaloneScrubber.java:72)
[cybersparta@cyber1 cybersparta]$


Thanks for the time
-Ravi

**Comment by rkgurram** [comment]
Hi,
    These are the logs that I get when I start cassandra,

INFO  [main] 2016-03-26 00:30:11,583 ColumnFamilyStore.java:339 - Initializing cybersparta.correlatedevents
INFO  [SSTableBatchOpen:1] 2016-03-26 00:30:11,585 SSTableReader.java:471 - Opening bin/../data/data/cybersparta/correlatedeven                ts-ef9c61b0d7d411e5b6b293ac61d720ce/cybersparta-correlatedevents-ka-117 (9316843 bytes)
INFO  [SSTableBatchOpen:2] 2016-03-26 00:30:11,585 SSTableReader.java:471 - Opening bin/../data/data/cybersparta/correlatedeven                ts-ef9c61b0d7d411e5b6b293ac61d720ce/cybersparta-correlatedevents-ka-116 (36053402 bytes)
INFO  [SSTableBatchOpen:3] 2016-03-26 00:30:11,586 SSTableReader.java:471 - Opening bin/../data/data/cybersparta/correlatedeven                ts-ef9c61b0d7d411e5b6b293ac61d720ce/cybersparta-correlatedevents-ka-70 (344144136 bytes)
INFO  [SSTableBatchOpen:4] 2016-03-26 00:30:11,586 SSTableReader.java:471 - Opening bin/../data/data/cybersparta/correlatedeven                ts-ef9c61b0d7d411e5b6b293ac61d720ce/cybersparta-correlatedevents-ka-111 (311517767 bytes)
INFO  [main] 2016-03-26 00:30:11,711 Log.java:43 - Initializing Lucene index
INFO  [main] 2016-03-26 00:30:11,796 Log.java:43 - Initialized index cybersparta.correlatedevents.correlatedevents_index
INFO  [main] 2016-03-26 00:30:11,801 ColumnFamilyStore.java:339 - Initializing cybersparta.asalogevents
ERROR [main] 2016-03-26 00:30:11,806 Log.java:85 - 'schema' is invalid : No column definition 'DURATION' for mapper 'DURATION'
ERROR [main] 2016-03-26 00:30:11,809 CassandraDaemon.java:541 - Exception encountered during startup
com.stratio.cassandra.lucene.IndexException: 'schema' is invalid : No column definition 'DURATION' for mapper 'DURATION'
        at com.stratio.cassandra.lucene.IndexConfig.parseSchema(IndexConfig.java:204) ~[cassandra-lucene-index-plugin-2.1.8.2.j                ar:na]
        at com.stratio.cassandra.lucene.IndexConfig.<init>(IndexConfig.java:74) ~[cassandra-lucene-index-plugin-2.1.8.2.jar:na]
        at com.stratio.cassandra.lucene.Index.validateOptions(Index.java:194) ~[cassandra-lucene-index-plugin-2.1.8.2.jar:na]
        at org.apache.cassandra.db.index.SecondaryIndex.createInstance(SecondaryIndex.java:364) ~[apache-cassandra-2.1.8.jar:2.                1.8]
        at org.apache.cassandra.db.index.SecondaryIndexManager.addIndexedColumn(SecondaryIndexManager.java:281) ~[apache-cassan                dra-2.1.8.jar:2.1.8]
        at org.apache.cassandra.db.ColumnFamilyStore.<init>(ColumnFamilyStore.java:367) ~[apache-cassandra-2.1.8.jar:2.1.8]
        at org.apache.cassandra.db.ColumnFamilyStore.createColumnFamilyStore(ColumnFamilyStore.java:504) ~[apache-cassandra-2.1                .8.jar:2.1.8]
        at org.apache.cassandra.db.ColumnFamilyStore.createColumnFamilyStore(ColumnFamilyStore.java:475) ~[apache-cassandra-2.1                .8.jar:2.1.8]
        at org.apache.cassandra.db.Keyspace.initCf(Keyspace.java:339) ~[apache-cassandra-2.1.8.jar:2.1.8]
        at org.apache.cassandra.db.Keyspace.<init>(Keyspace.java:279) ~[apache-cassandra-2.1.8.jar:2.1.8]
        at org.apache.cassandra.db.Keyspace.open(Keyspace.java:121) ~[apache-cassandra-2.1.8.jar:2.1.8]
        at org.apache.cassandra.db.Keyspace.open(Keyspace.java:98) ~[apache-cassandra-2.1.8.jar:2.1.8]
        at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:324) [apache-cassandra-2.1.8.jar:2.1.8]
        at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:524) [apache-cassandra-2.1.8.jar:2.1.8]
        at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:613) [apache-cassandra-2.1.8.jar:2.1.8]


Regards
-Ravi

**Comment by adelapena** [comment]
I see. The SStables are no corrupted, just unable to be read because of the index wrong setup. This problem was fixed some versions ago. Upgrade the plugin JAR file to 2.1.8.5 and try to run the nodes again. If it goes well, drop the index and create it again. If not, you should manually remove the index metadata from system keyspace to force Cassandra to forget it.

**Comment by rkgurram** [comment]
Hi Adalapena,
    Thank you for the response, I will try that version of lucene cassandra index, in case it does not work I want to manually remove the index metadata from the system keyspace. How do I do it? I have searched on google but am unable to find that, it will be great if you can send me a few pointers. Thanks again it has been of immense help.

Regards
-Ravi

**Comment by rkgurram** [comment]
Hi Adalapena,
    As suggested I tried the plugin 2.1.8.5 and it is still failing. The output us as follows,
======================================================================
INFO  [SSTableBatchOpen:3] 2016-03-26 02:00:28,727 SSTableReader.java:471 - Opening bin/../data/data/cybersparta/correlatedevents-ef9c61b0d7d411e5b6b293ac61d720ce/cybersparta-correlatedevents-ka-70 (344144136 bytes)
INFO  [SSTableBatchOpen:4] 2016-03-26 02:00:28,734 SSTableReader.java:471 - Opening bin/../data/data/cybersparta/correlatedevents-ef9c61b0d7d411e5b6b293ac61d720ce/cybersparta-correlatedevents-ka-111 (311517767 bytes)
INFO  [main] 2016-03-26 02:00:28,848 Index.java:93 - Initializing Lucene index
INFO  [main] 2016-03-26 02:00:28,938 Index.java:101 - Initialized index cybersparta.correlatedevents.correlatedevents_index
INFO  [main] 2016-03-26 02:00:28,945 ColumnFamilyStore.java:339 - Initializing cybersparta.asalogevents
ERROR [main] 2016-03-26 02:00:28,953 CassandraDaemon.java:541 - Exception encountered during startup
java.lang.RuntimeException: org.apache.cassandra.exceptions.ConfigurationException: 'schema' is invalid : No column definition 'DURATION' for mapper 'DURATION'
        at org.apache.cassandra.db.index.SecondaryIndexManager.addIndexedColumn(SecondaryIndexManager.java:285) ~[apache-cassandra-2.1.8.jar:2.1.8]
        at org.apache.cassandra.db.ColumnFamilyStore.<init>(ColumnFamilyStore.java:367) ~[apache-cassandra-2.1.8.jar:2.1.8]
        at org.apache.cassandra.db.ColumnFamilyStore.createColumnFamilyStore(ColumnFamilyStore.java:504) ~[apache-cassandra-2.1.8.jar:2.1.8]
        at org.apache.cassandra.db.ColumnFamilyStore.createColumnFamilyStore(ColumnFamilyStore.java:475) ~[apache-cassandra-2.1.8.jar:2.1.8]
        at org.apache.cassandra.db.Keyspace.initCf(Keyspace.java:339) ~[apache-cassandra-2.1.8.jar:2.1.8]
        at org.apache.cassandra.db.Keyspace.<init>(Keyspace.java:279) ~[apache-cassandra-2.1.8.jar:2.1.8]
        at org.apache.cassandra.db.Keyspace.open(Keyspace.java:121) ~[apache-cassandra-2.1.8.jar:2.1.8]
        at org.apache.cassandra.db.Keyspace.open(Keyspace.java:98) ~[apache-cassandra-2.1.8.jar:2.1.8]
        at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:324) [apache-cassandra-2.1.8.jar:2.1.8]
        at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:524) [apache-cassandra-2.1.8.jar:2.1.8]
        at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:613) [apache-cassandra-2.1.8.jar:2.1.8]
Caused by: org.apache.cassandra.exceptions.ConfigurationException: 'schema' is invalid : No column definition 'DURATION' for mapper 'DURATION'
        at com.stratio.cassandra.lucene.Index.validateOptions(Index.java:145) ~[cassandra-lucene-index-plugin-2.1.8.5-SNAPSHOT.jar:na]
        at org.apache.cassandra.db.index.SecondaryIndex.createInstance(SecondaryIndex.java:364) ~[apache-cassandra-2.1.8.jar:2.1.8]
        at org.apache.cassandra.db.index.SecondaryIndexManager.addIndexedColumn(SecondaryIndexManager.java:281) ~[apache-cassandra-2.1.8.jar:2.1.8]
        ... 10 common frames omitted
Caused by: com.stratio.cassandra.lucene.IndexException: 'schema' is invalid : No column definition 'DURATION' for mapper 'DURATION'
        at com.stratio.cassandra.lucene.IndexConfig.parseSchema(IndexConfig.java:285) ~[cassandra-lucene-index-plugin-2.1.8.5-SNAPSHOT.jar:na]
        at com.stratio.cassandra.lucene.IndexConfig.<init>(IndexConfig.java:83) ~[cassandra-lucene-index-plugin-2.1.8.5-SNAPSHOT.jar:na]
        at com.stratio.cassandra.lucene.Index.newIndexConfig(Index.java:198) ~[cassandra-lucene-index-plugin-2.1.8.5-SNAPSHOT.jar:na]
        at com.stratio.cassandra.lucene.Index.validateOptions(Index.java:142) ~[cassandra-lucene-index-plugin-2.1.8.5-SNAPSHOT.jar:na]
        ... 12 common frames omitted
Caused by: com.stratio.cassandra.lucene.IndexException: No column definition 'DURATION' for mapper 'DURATION'
        at com.stratio.cassandra.lucene.schema.mapping.Mapper.validate(Mapper.java:175) ~[cassandra-lucene-index-plugin-2.1.8.5-SNAPSHOT.jar:na]
        at com.stratio.cassandra.lucene.schema.mapping.Mapper.validate(Mapper.java:161) ~[cassandra-lucene-index-plugin-2.1.8.5-SNAPSHOT.jar:na]
        at com.stratio.cassandra.lucene.schema.Schema.validate(Schema.java:162) ~[cassandra-lucene-index-plugin-2.1.8.5-SNAPSHOT.jar:na]
        at com.stratio.cassandra.lucene.IndexConfig.parseSchema(IndexConfig.java:283) ~[cassandra-lucene-index-plugin-2.1.8.5-SNAPSHOT.jar:na]
        ... 15 common frames omitted


Regards
-Ravi

**Comment by adelapena** [comment]
Currently I'm far away from my computer so I won't be able to provide a hotfix until tuesday. Until then, you can modify the method com.stratio.cassandra.lucene.Index#validateOptions to catch all exceptions and recompile the plugin. It probably would be enough to startup the node and be able to delete the index and create it again.

**Comment by rkgurram** [comment]
Hi Adelapena,
    Thank you for the suggestion, it was a godsend. I thought I had lost all the data now the nodes are all back. I did make the change as suggested and Cassandra did come up and I dropped all the indices and  re-created them. Now the system is back in action with no loss of any data. 

Thanks again, I will wait for the hotfix.

Regards
-Ravi

**Comment by adelapena** [comment]
Hi @rkgurram,

I'm trying to reproduce the problem. I create a keyspace and a table:
```
CREATE KEYSPACE demo WITH REPLICATION = {'class' : 'SimpleStrategy',  'replication_factor': 1};

CREATE TABLE demo.users (
  name varchar, 
  lucene text, 
  PRIMARY KEY (name));
```
And then I create a index with a wrong column name to simulate the initial typo:
```
CREATE CUSTOM INDEX demo_lucene ON  demo.users (lucene) USING 'com.stratio.cassandra.lucene.Index' WITH OPTIONS = {
 'refresh_seconds':'1',  
 'schema':'{fields:{mane:{type:"string"}}}'
 };
```
As expected, I receive an error:
```
ServerError: <ErrorMessage code=0000 [Server error] message="com.stratio.cassandra.lucene.IndexException: 'schema' is invalid : No column definition 'mane' for mapper 'mane'">
```
Then I have tried to properly shutdown the node with ``nodetool drain``, ``kill`` and ``kill -9``, but the node always start without any problem; the index is just never created so it can't produce a failure during startup. I have also tried with a small ccm cluster.

Could you please provide some additional information about how to reproduce the failure scenario? Were you using 2.1.8.2? When/how did the problem start?

Thanks in advance,

**Comment by rkgurram** [comment]
Hi Andres,
    Yes I was using cassandra-lucene-index-plugin-2.1.8.2.jar, 

The scenario that my associate followed was  as follows,
1) Create a table and corresponding index for a given set of fields
2) Ensure that both table and index are correct as far as the column names are concerned
3) Change the column name in the table but **forgot ** to change the column name in index
4) Cassandra was running fine for a few hours and then we realized some of the instances had crashed
4) Bring down cassandra on all nodes and bring it back up, it fails with that error

Hope this helps

Regards
-Ravi

**Comment by adelapena** [comment]
Hi @rkgurram,

I see. The problem is due to how Cassandra validates indexes. From Cassandra 3.x, attempts to alter an indexed column are properly avoided with this message, independently of the index implemetation:
```
InvalidRequest: code=2200 [Invalid query] message="Cannot rename column name because it has dependent secondary indexes (test)"
```
And there is an equivalent message for attempts to delete an indexed column:
```
InvalidRequest: code=2200 [Invalid query] message="Cannot drop column ColumnDefinition{name=name, type=org.apache.cassandra.db.marshal.UTF8Type, kind=REGULAR, position=-1} because it has dependent secondary indexes (test)"
```
Unfortunately, this is not checked in Cassandra 2.x. Take a look to the ```renameColumn``` method in both versions:
- [renameColumn in Cassandra 3.0.4](https://github.com/apache/cassandra/blob/cassandra-3.0.4/src/java/org/apache/cassandra/config/CFMetaData.java#L958)
- [renameColumn in Cassandra 2.1.8](https://github.com/apache/cassandra/blob/cassandra-2.1.8/src/java/org/apache/cassandra/config/CFMetaData.java#L2004)

Fixing this would involve to open a ticket in [Apache Cassandra JIRA](https://issues.apache.org/jira/browse/CASSANDRA), and it would probably not be applied to 2.1.x. As a walk around, we will publish a hotfix to just skip index schema validation if the index has been already created. It will still require an index rebuild to update the schema, but it will avoid the startup failure. This fix will be available along this week.

Thanks for your help.

**Comment by adelapena** [comment]
Hi,

We have just released [2.1.8.6](https://github.com/Stratio/cassandra-lucene-index/tree/2.1.8.6) fixing the problem. If you alter/delete an indexed column without deleting the index, it just logs an error message about the inconsistency between the index and the indexed table schemas.

This fix will be propagated to newer 2.x versions.

I hope it helps.

**Comment by rkgurram** [comment]
Hi Andres,
    This is of great help. Will quickly get this release into our build and
do a sanity. Thanks a ton for your quick response and help, it saved us
quite a lot of effort and more importantly the data.

Thanks & Regards
-Ravi
