### ISSUE TITLE
BackgroundCompaction causes Node crash (OutOfMemoryError)

### ISSUE THREAD

**Issue by juvlarN** [Stratio/cassandra-lucene-index#190]
Hi,

I have the problem as outlined in this JIRA: https://issues.apache.org/jira/browse/CASSANDRA-12477 
You can find a system.log file attached to the JIRA issue. I ran it with -XX:MaxDirectMemorySize=16G. 

About 300-400 MB of raw data will hit each node. My Cassandra-Lucene-Index is enabled on the table. 
I get node crashes due to OutOfMemoryErrors. When restarting the node, the node tries to replay the data from the commit log (I guess?) and then dies again because of an OutOfMemoryError.

I need to insert bulk data from time to time. 
How to deal with this? Is adjusting "-XX:MaxDirectMemorySize" the way to go here? 16G did not help.

**Comment by ealonsodb** [comment]
Hi @juvlarN 
As stated in [CASSANDRA-12477]( https://issues.apache.org/jira/browse/CASSANDRA-12477), it seems to be [CASSANDRA-11710](https://issues.apache.org/jira/browse/CASSANDRA-11710) affecting cassandra 3.0.8. 

Looking for the exact commit id that Jake Luciani points here[CASSANDRA-11710](https://issues.apache.org/jira/browse/CASSANDRA-11710) results in these changes: [31cab36b1800f2042623633445d8be944217d5a2](https://github.com/apache/cassandra/commit/31cab36b1800f2042623633445d8be944217d5a2)

The [commit](https://github.com/apache/cassandra/commit/31cab36b1800f2042623633445d8be944217d5a2) is relatively easy to patch into cassandra 3.0.8 and try if it works. 

Hope this helps you.

**Comment by juvlarN** [comment]
Hi @ealonsodb,

I will build a version with that fix later today and report back tomorrow.
I have yet to find out how to reproduce the error though. 
In the meantime, I've set the "-XX:MaxDirectMemorySize" to 26G and it worked without throwing exceptions...

So this issue is not related to the cassandra-lucene-index project? 
I guess you can close the issue then.

Thanks

**Comment by ealonsodb** [comment]
I think the error is [CASSANDRA-11710](https://issues.apache.org/jira/browse/CASSANDRA-11710). Please report us if the patched 3.0.8 version of cassandra works.

Are you kuku1 in [CASSANDRA-12477](https://issues.apache.org/jira/browse/CASSANDRA-12477)? If so, you are using cassandra-lucene-index:3.0.8.0 and you should use [3.0.8.2](https://github.com/Stratio/cassandra-lucene-index/tree/3.0.8.2).

Last commits in [branch-3.0.8](https://github.com/Stratio/cassandra-lucene-index/commits/branch-3.0.8) will be merged into [branch-3.7](https://github.com/Stratio/cassandra-lucene-index/commits/branch-3.7) ASAP

Read more about [tick-tock](http://www.planetcassandra.org/blog/cassandra-2-2-3-0-and-beyond/) here but IMHO you must not use 3.x cassandra versions in production systems.

Thank you for your effort

**Comment by ealonsodb** [comment]
Hi @juvlarN:

i just want to let you know we've released [3.7.2](https://github.com/Stratio/cassandra-lucene-index/tree/3.7.2) including last commits in [branch-3.0.8](https://github.com/Stratio/cassandra-lucene-index/tree/branch-3.0.8)

**Comment by juvlarN** [comment]
I can't seem to reproduce this with the 3.0.8 version I built. I am using the same importer application to ingest data. I think this should be resolved with the fix you mentioned! I will reopen the ticket when I stumble across related errors.

**Comment by ealonsodb** [comment]
Hi @juvlarN: 

-Direct buffer memory is a memory section inside JVM off-heap. This is NOT inside heap, so increasing heap limit does not solve your problem.

-Cassandra benefits from OS disk cache, so it is not recomendable to use all node RAM inside cassandra process. Please read [Tuning Java resource](http://docs.datastax.com/en/cassandra/3.0/cassandra/operations/opsTuneJVM.html) to choose the correct values.

- When writing one wide row in cassandra with an associated lucene index, it force the index to read all the entire wide row to index it properly. This is costly, so it should be used carefully.

Inserting 20Gb(for example 100K inserts) of data asyncly will not stop sending inserts (100K) to cassandra cluster. So cluster becomes overloaded especially those two nodes(maybe your data is not well balanced or just a bunch of inserts touch those nodes in a short period of time). 

We use a [BlockingExecutor](https://github.com/jmiddleton/cassandra-fhir-index/blob/master/fhir-index-plugin/src/main/java/io/puntanegra/fhir/index/util/BlockingExecutor.java) with a fixed maximum number of threads that perform inserts syncly. With this way you can limit the max concurrent executing inserts in the cluster(the number of threads) and will not overload the cluster. You can play with the poolSize(thread pool size) and queueSize(size of queue) to get the most efficient params that do not overload your cluster.

Try this way and let us know please.

**Comment by juvlarN** [comment]
Hi @ealonsodb,

I was using "non-tuned" memory settings when I inserted my data. I let Cassandra choose the RAM amount because that's usually a good way to do (at least that's what I read, IIRC). I was just running with the large amount of RAM to get the nodes back up. They were not able to start otherwise. I have now removed the RAM allocation again because they have "fixed" their startup process.

My importer application is writing out async inserts until a threshold of concurrently running inserts exceeds a limit. When an async insert is executed, the corresponding `ResultSetFuture` will be saved to a list and another thread waits for the insert to finish and then removes it from the list of running `ResultSetFuture` objects. 

I will try out your BlockingExecutor tomorrow and see what happens.

**Comment by juvlarN** [comment]
Is it possible to stop indexing until I allow the creation of indexes again? I would like to insert all my data first, then let the index creation start when all data has been transmitted. 

Something is going wrong when I insert 40.000.000 rows. The writes seem to get accepted by Cassandra because my "concurrent insert count" is never higher than ~15-20, most of the time at just 0 or 1. The importer application is never seeing any blocking from Cassandras side. But with the index enabled, some nodes (mostly one or two) die while importing the same data. 

Maybe the async index creation setting [indexing_threads](https://github.com/Stratio/cassandra-lucene-index/blob/branch-3.0.8/doc/documentation.rst#indexing) is causing problems? Will setting this setting to 0 process all incoming data synchronously? Will the index-queue be able to handle the amount of rows being inserted? Will this slow down the insertion of more data or is it a seperate process?

**Comment by adelapena** [comment]
Indexing can only be stopped by deleting the index.

Asynchronous indexing pushes index writes into a set of fixed-size queues. When the queues are full they block the client, applying a back-pressure strategy. Setting `ìndexing_threads`` to 0 will disable this queues and will do all index writes synchronous. That is, each client write will be blocked until the data is indexed in the number of replicas determined by the chosen write consistency level.
